/**:
  ros__parameters:
    # --- ค่าแปลงหน่วย (Calibration) ---
    speed_to_erpm_gain: 3750.0
    speed_to_erpm_offset: 0.0
    steering_angle_to_servo_gain: -1.213
    steering_angle_to_servo_offset: 0.5304

    # --- ปลดล็อคขีดจำกัด (Limits) ต้องใส่ให้ครบไม่งั้นมันจะเป็น 0 ---
    servo_min: 0.0
    servo_max: 1.0

    # --- ปลดล็อคความเร็ว ---
    speed_min: -20000.0
    speed_max: 20000.0
    duty_cycle_min: 0.0
    duty_cycle_max: 0.95
    current_min: 0.0
    current_max: 100.0
